apiVersion: scaffolder.backstage.io/v1beta3
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template
kind: Template
metadata:
  name: example-run-testworkflow
  title: Example Run Testworkflow Template
  description: An example template for the scaffolder that runs a Testkube workflow
spec:
  owner: user:guest
  type: service

  # These parameters are used to generate the input form in the frontend, and are
  # used to gather input data for the execution of the template.
  parameters: []

  # These steps are executed in the scaffolder backend, using data that we gathered
  # via the parameters above.
  steps:

    # Run the Testkube quality gate after the component is registered.
    - id: testkube
      name: Run Testkube quality gate
      action: testkube:run-test-workflows
      input:
        workflows:
          - name: k6-sample
          - name: postman-junit-report
        orgId: tkcorg_0f382d90e81ea228
        envId: tkcenv_943fe797cb48b4d2
        timeoutSeconds: 1800

  # Outputs are displayed to the user after a successful execution of the template.
  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
